//
//  Convenience.swift
//  SwiftResponsesDSL
//
//  Convenience functions and helpers
//
//  Generated by AI-assisted code generation.
//  Created by Richard Naszcyniec on [Date].
//  Copyright © [Year] Richard Naszcyniec. All rights reserved.
//

import Foundation

// MARK: - Convenience Functions

/// Creates a system message
public func system(_ text: String) -> SystemMessage {
    SystemMessage(text: text)
}

/// Creates a user message
public func user(_ text: String) -> UserMessage {
    UserMessage(text: text)
}

/// Creates a user message with file
public func user(_ text: String, fileId: String) -> UserMessage {
    UserMessage(role: .user, content: [.text(text), .inputFile(fileId: fileId)])
}

/// Creates an assistant message
public func assistant(_ text: String) -> AssistantMessage {
    AssistantMessage(text: text)
}

/// Creates a tool message
public func tool(_ text: String) -> UserMessage {
    UserMessage(role: .tool, text: text)
}
