version: 2
updates:
  # Enable version updates for Swift packages
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "RichNasz"
    assignees:
      - "RichNasz"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    reviewers:
      - "RichNasz"
    assignees:
      - "RichNasz"
    commit-message:
      prefix: "ci"
      include: "scope"
